### ISSUE TITLE
Can we mark this deprecated?

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/docker-icinga2-demo#16]
I think it would make sense to mark this repo deprecated.

Or is there anyone that wants to maintain it?

Anyone oppose deprecation? @bobapple @dnsmichi /cc @dgoetz

**Comment by dgoetz** [comment]
As always It is nice to have this kind of demo as long as it is maintained, so if unmaintained we should deprecate it, but it would be better to replace it with something maintained. As far as I know is @bobapple already in contact with someone who wanted to help.

**Comment by dnsmichi** [comment]
Go for it. At the time I created the demo I did not know much about Docker, and that's nearly 3 years now. It doesn't hurt keeping the repo here, but at least issues shouldn't be dealt with.

**Comment by bobapple** [comment]
Currently I have no plans to continue this repository. If we're going to build an official Icinga 2 container some day, it will be a separate project.

**Comment by lazyfrosch** [comment]
Done, marked in description and README

**Comment by lazyfrosch** [comment]
Removed the image on Docker Hub, left a note inside [icinga/icinga2](https://hub.docker.com/r/icinga/icinga2/)

**Comment by ssbarnea** [comment]
Can we have some insights on why container based distribution was not adopted by icinga?

**Comment by lazyfrosch** [comment]
This is a community based project, none of our main contributors is currently interested in maintaining and supporting official images for Icinga 2 and add-ons.

There are some containers from the community though.

**Comment by dnsmichi** [comment]
You can try these which are pretty famous amongst community members.

https://github.com/bodsch/docker-icinga2
https://github.com/psi-4ward/docker-icinga2

**Comment by ssbarnea** [comment]
@lazyfrosch @dnsmichi Thanks for the update, I will have a look at them. 

Maybe it would worth asking these community members if they do not want to become maintainers of such a container, where its repository would be hosted under icinga hithub organization and published under icinga organization on docker hub. If they are passionate, I would refuse. You can still mention on the project that is not officially supported by the icinga core team. Think about Jenkins, were now all plugins are build and hosted under the same github organization, even if the core team does not support most of them, apparently it works well.

I am asking this because I am reluctant to install containers published under individual accounts, mainly due to two risks, security and also the risk of becoming unmaintained, which is always much bigger when a project depends on a single person.

**Comment by dnsmichi** [comment]
We've already talked with them, still maintaining such containers needs a little more than one person responsible. You'd need to ensure that the infrastructure for building such is in place, and you also need to deal with support questions. Not only on GitHub, but for the entire Icinga team with yet another method of installing the Icinga stack. This is something where I personally don't have the desire to add Docker support to my list of possible problems when helping community members.

I do understand the security implications one will have with custom built containers, yet you have the possibility to rebuild them for your own environment and use a local Docker registry for example. We'll see what the future brings here in terms of official images, right now we're focussing on other big project tasks and features.

**Comment by bodsch** [comment]
I do not plan to drop my support because I also use the containers in other projects.
In addition, the individual branches are regularly rebuilt via TravisCI and pushed into the registry.
 I hope to get the latest updates from Conatiner.

Furthermore, my projects are open source... if you like, fork it! :)
